In [1]:
import numpy as np

In [43]:
pred_list = [np.genfromtxt('pred_list.csv', delimiter=',')]
pred_list

[array([[6.10351562e-05, 1.98364258e-04, 4.57763672e-05, ...,
         1.52587891e-05, 9.15527344e-05, 3.20434570e-04],
        [1.67846680e-04, 7.17163086e-04, 5.79833984e-04, ...,
         3.05175781e-05, 7.62939453e-05, 1.08642578e-02]])]

In [44]:
predictions = np.concatenate(pred_list)

In [45]:
predictions.shape

(2, 1000)

In [38]:

from tensorflow.keras.applications.imagenet_utils import decode_predictions
dec_predictions = decode_predictions(predictions, top=1)
dec_predictions

[[('n03240683', 'drilling_platform', 0.1872711181640625)],
 [('n03729826', 'matchstick', 0.0376129150390625)]]

In [39]:
predictions = predictions.argmax(1).reshape(-1, 1)
predictions

array([[540],
       [644]])

In [40]:
labels = np.array([[481], [350]], dtype="int64")
labels = labels.reshape(-1, 1)
labels

array([[481],
       [350]])

In [42]:
sum(labels == predictions)

array([0])

In [59]:
def measure_precision_loss(plaintext_pred, enc_pred):
    if plaintext_pred is None or enc_pred is None:
        return None
    assert plaintext_pred.shape == enc_pred.shape
    diff = plaintext_pred - enc_pred
    abs_ = np.absolute(diff)
    return np.average(abs_, axis=(0,1))

In [60]:
measure_precision_loss(predictions, predictions)

0.0

In [69]:
measure_precision_loss(predictions, np.random.random(predictions.shape))

0.4935381962947085

In [56]:
plaintext_pred = predictions
enc_pred = np.random.random(predictions.shape)

In [58]:
np.absolute(plaintext_pred - enc_pred)

array([[0.23017039, 0.647896  , 0.18557301, ..., 0.63351706, 0.88913079,
        0.76381992],
       [0.76617306, 0.32248856, 0.60035343, ..., 0.56823053, 0.74407467,
        0.83800523]])